### ISSUE TITLE
Unable to bind PVC

### ISSUE THREAD

**Issue by totallyGreg** [democratic-csi/democratic-csi#6]
Struggling to make this work. 

I'm running 1.17 (all feature flags should be present by default now) via Rancher.  

I have installed it via a helm chart with my own values.yml and everything seems to be running successfully.  
I am passing the driver.config.sshConnection.password in via the --set-string parameter of helm upgrade.  
I do not fully understand the kubernetes secrets that are automatically created via the helm chart.  e.g. 
provisioner-secret-test-csi-zfs-nfs-democratic-csi which is empty of any value.  

```
❯ k get pods
NAME                                                READY   STATUS    RESTARTS   AGE
zfs-nfs-democratic-csi-controller-dd995d468-jr4r8   5/5     Running   0          32m
zfs-nfs-democratic-csi-node-hgd64                   3/3     Running   0          31m
zfs-nfs-democratic-csi-node-ntgfc                   3/3     Running   0          30m
zfs-nfs-democratic-csi-node-qxk2q                   3/3     Running   0          31m
```

I've created a pod that requests storage from the test-csi storage class i've created that  points to my zpool on freenas:
FreeBSD 11.3-RELEASE-p9 (FreeNAS.amd64) #0 r325575+588899735f7(HEAD): Mon Jun  1 15:04:31 EDT 2020

```
❯ k get sc test-csi
NAME       PROVISIONER              RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
test-csi   org.democratic-csi.nfs   Delete          Immediate           true                   15h

❯ k get pvc
NAME       STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
test-pvc   Pending                                      test-csi       12m
```

Errors that show up immediately after provisioning the pod.  
```
zfs-nfs-democratic-csi-controller-dd995d468-jr4r8 external-provisioner E0705 18:12:27.596513       1 controller.go:910] error syncing claim "bbfaae8e-fdd2-420e-8981-219fbadc5a29": failed to provision volume with StorageClass "test-csi": rpc error: code = Internal desc = TypeError: Cannot read property 'replace' of null
zfs-nfs-democratic-csi-controller-dd995d468-jr4r8 external-provisioner I0705 18:12:27.598071       1 event.go:255] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"democratic-csi", Name:"test-pvc", UID:"bbfaae8e-fdd2-420e-8981-219fbadc5a29", APIVersion:"v1", ResourceVersion:"34310635", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "test-csi": rpc error: code = Internal desc = TypeError: Cannot read property 'replace' of null
zfs-nfs-democratic-csi-controller-dd995d468-jr4r8 csi-driver info: new request - driver: FreeNASDriver method: CreateVolume call: {"_events":{},"_eventsCount":1,"call":{},"cancelled":false,"metadata":{"_internal_repr":{"user-agent":["grpc-go/1.19.1"]},"flags":0},"request":{"volume_capabilities":[{"access_mode":{"mode":"MULTI_NODE_MULTI_WRITER"},"mount":{"mount_flags":["nfsvers=4.1","intr","rsize=16384","wsize=16384"],"fs_type":"nfs"},"access_type":"mount"}],"parameters":{"fsType":"nfs"},"secrets":"redacted","name":"pvc-bbfaae8e-fdd2-420e-8981-219fbadc5a29","capacity_range":{"required_bytes":"1048576","limit_bytes":"0"},"volume_content_source":null,"accessibility_requirements":null}}
zfs-nfs-democratic-csi-controller-dd995d468-jr4r8 csi-driver {
zfs-nfs-democratic-csi-controller-dd995d468-jr4r8 csi-driver   code: 13,
zfs-nfs-democratic-csi-controller-dd995d468-jr4r8 csi-driver   message: "TypeError: Cannot read property 'replace' of null"
zfs-nfs-democratic-csi-controller-dd995d468-jr4r8 csi-driver }
zfs-nfs-democratic-csi-controller-dd995d468-jr4r8 csi-driver error: handler error - driver: FreeNASDriver method: CreateVolume error: {}
```

Any help would be greatly appreciated.  Honestly IX should be paying you to work on this project.

**Comment by travisghansen** [comment]
@totallyGreg Hey! I'm sure we can get you going. I'm surprised you've gotten as far as you have as I have pretty much 0 documentation (planning to fix that shortly actually).

So that error is likely from a string operation. Unfortunately we don't have the backtrace there but I'm guessing I'm not using `replace` in very many places. Let me have a quick look and see what I find...

**Comment by travisghansen** [comment]
OK, can you cleanse the `values.yaml` (assuming you used helm) and send it my way? Also can you send over the storage class definition? Also, do you know if the dataset was actually created on the FreeNAS machine? I'm trying to gauge how far along the `CreateVolume` request is getting before hitting the error to help narrow down what could be resulting in the issue.

The `secrets` can effectively be ignored (particularly with nfs). I mostly added those to the chart because the project (and chart) is actually meant to support more than just FreeNAS (it actually already works 100% with ZoL with Ubuntu for example). With the iscsi deployments you'll need to use them if you're using `CHAP`.

**Comment by totallyGreg** [comment]
I would assume one of the secrets would be used to store the connection credentials to the freenas server (http or ssh) much like the freenas-nfs-provisioner did. Which is why I uncommented the provisioner secret thinking it would be used.   As mentioned above I am currently just setting this by passing in the value to helm upgrade.  

```
❯ k describe sc test-csi
Name:                  test-csi
IsDefaultClass:        No
Annotations:           meta.helm.sh/release-name=zfs-nfs,meta.helm.sh/release-namespace=democratic-csi
Provisioner:           org.democratic-csi.nfs
Parameters:            csi.storage.k8s.io/provisioner-secret-name=provisioner-secret-test-csi-zfs-nfs-democratic-csi,csi.storage.k8s.io/provisioner-secret-namespace=democratic-csi,fsType=nfs
AllowVolumeExpansion:  True
MountOptions:
  nfsvers=4.1
  intr
  rsize=16384
  wsize=16384
ReclaimPolicy:      Delete
VolumeBindingMode:  Immediate
Events:             <none>
```
The values here are pretty generic (no domains and non-routable ip's)
```
# Default values for democratic-csi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

driver:
  config: # {}
    driver: freenas-nfs
    instance_id:
    sshConnection:
      host: freenasty-int
      port: 22
      username: root
      # use either password or key
      password: ""
    zfs:
      datasetParentName: zapool/NFS/test
      detachedSnapshotsDatasetParentName:
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: root
      datasetPermissionsGroup: wheel
    nfs:
      shareHost: freenasty-int.home.falcone.us
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks: [10.0.0.0/24 10.0.1.0/24 10.0.10.0/24 10.42.0.0/16 10.43.0.0/16]
      shareMaprootUser: root
      shareMaprootGroup: wheel
      shareMapallUser: ""
      shareMapallGroup: ""

# https://kubernetes-csi.github.io/docs/csi-driver-object.html
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.nfs"
  version: 1.1.0
  # create the kubernetes CSIDriver
  enabled: true
  attachRequired: false
  podInfoOnMount: true
  # clusters before 1.14 requeired manual installation
  # kubectl create -f https://raw.githubusercontent.com/kubernetes/csi-api/master/pkg/crd/manifests/csidriver.yaml
  installCRD: false

controller:
  rbac:
    enabled: true
  replicaCount: 1
  enabled: true

  # https://kubernetes-csi.github.io/docs/external-provisioner.html
  externalProvisioner:
    enabled: true

  # https://kubernetes-csi.github.io/docs/external-resizer.html
  externalResizer:
    enabled: true

  # https://kubernetes-csi.github.io/docs/external-snapshotter.html
  externalSnapshotter:
    enabled: true

  # https://kubernetes-csi.github.io/docs/cluster-driver-registrar.html
  # not implemented, likely uncessary at this point
  clusterDriverRegistrar:
    enabled: false

  # https://kubernetes-csi.github.io/docs/livenessprobe.html
  livenessProbe:
    enabled: true

  # democratic-csi controller
  driver:
    enabled: true
    logLevel: debug

node:
  rbac:
    enabled: true
  enabled: true

  # democratic-csi node
  driver:
    enabled: true
    logLevel: debug

  # https://kubernetes-csi.github.io/docs/node-driver-registrar.html
  driverRegistrar:
    enabled: true

# add note here about volume expansion requirements
storageClasses: # []
- name: test-csi
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    # for block-based storage can be ext3, ext4, xfs
    # for nfs should be nfs
    fsType: nfs
  mountOptions: [nfsvers=4.1,intr,rsize=16384,wsize=16384]
  secrets:
    provisioner-secret:
    # controller-publish-secret:
    # node-stage-secret:
    # node-publish-secret:
    # controller-expand-secret:

volumeSnapshotClasses: []
#- name:
#  parameters:
#  secrets:
#    snapshotter-secret:
```

**Comment by travisghansen** [comment]
I think it does create the config as a secret yes. Was thinking of all the others.

I’ll start digging through the code to see where replace is invoked. Did you notice if the dataset was created in FreeNAS or is it puking before it even gets there?

**Comment by totallyGreg** [comment]
Dataset is not getting created (I updated my comment above when I realized I failed to put that in there :)

**Comment by travisghansen** [comment]
Ok, can you add `httpConnection` block into the config with appropriate values and just see (doubt it will fix the problem but it will be required regardless).

**Comment by travisghansen** [comment]
Basically all zfs operations go over ssh the limit the crazy API issues with FreeNAS, but the share creation bits (for both nfs and iscsi) still use the http API.

**Comment by totallyGreg** [comment]
okay added httpConnection (and password with set-string and upgraded the helm chart).  Didn't seem to make a difference.
Shouldn't have to but I deleted and recreated the pod as well.  
  
```
❮ k describe pvc
Name:          test-pvc
Namespace:     democratic-csi
StorageClass:  test-csi
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: org.democratic-csi.nfs
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type     Reason                Age              From                                                                                                            Message
  ----     ------                ----             ----                                                                                                            -------
  Normal   ExternalProvisioning  6s               persistentvolume-controller                                                                                     waiting for a volume to be created, either by external provisioner "org.democratic-csi.nfs" or manually created by system administrator
  Normal   Provisioning          3s (x3 over 6s)  org.democratic-csi.nfs_zfs-nfs-democratic-csi-controller-58d9f9b84c-5c8tp_54028808-fb3b-4593-90f4-5d5b7737917a  External provisioner is provisioning volume for claim "democratic-csi/test-pvc"
  Warning  ProvisioningFailed    3s (x3 over 6s)  org.democratic-csi.nfs_zfs-nfs-democratic-csi-controller-58d9f9b84c-5c8tp_54028808-fb3b-4593-90f4-5d5b7737917a  failed to provision volume with StorageClass "test-csi": rpc error: code = Internal desc = TypeError: Cannot read property 'replace' of null
```

**Comment by travisghansen** [comment]
That sounds like another thing I need to add to the chart if it didn’t cycle the pods on it’s own..

**Comment by totallyGreg** [comment]
i just meant the test pod that make the test-pvc.

**Comment by travisghansen** [comment]
Ah ok. I think I had some env vars to set that should spew extra stuff out to get a better idea what’s going on. Let me go dig it up..

**Comment by travisghansen** [comment]
I'm fairly sure it's this: `detachedSnapshotsDatasetParentName`

I would do my configuration like this:

```
      datasetParentName: zapool/NFS/test/v
      detachedSnapshotsDatasetParentName: zapool/NFS/test/s
```

or `vols` and `snaps` instead of `v` and `s`.

I will be updating the charts relatively soon to function properly with the snapshot beta (it was a pretty big change going from alpha to beta unfortunately with k8s).

**Comment by travisghansen** [comment]
Technically, you could put detached snapshots on a totally separate `pool` if you wanted to be really safe as an FYI. Unfortunately, I never implemented remote snapshots (ie: send/receive to a pool on another node) but it's my intent at some point.

**Comment by totallyGreg** [comment]
okay I configured
```detachedSnapshotsDatasetParentName:  zapool/NFS/test/s```

Not sure why this is necessary if I'm not actually mounting my snapshots as volumes and not replicating them anywhere.
This does seem to fix the null error.   👍 

There was a complaint about not finding the hostname, so I added the FQDN and that solved that complaint.  

I have set the root password in a variable and I am passing that variable to the helm upgrade
```
 ❯ helm upgrade --install -n democratic-csi zfs-nfs democratic-csi/democratic-csi -f 02-freenas-nfs/democratic-csi.yml --set-string driver.config.sshConnection.password=$PASS --set-string driver.config.httpConnection.password=$PASS
```

Unfortunately I am still getting an issue with the pvc.  
``` 
Warning  ProvisioningFailed    18s (x4 over 2m26s)    org.democratic-csi.nfs_zfs-nfs-democratic-csi-controller-68c7f7b465-lmjcg_e6d8e5b6-6c32-4a5f-aceb-72173461c8a2  failed to provision volume with StorageClass "test-csi": rpc error: code = Internal desc = Error: All configured authentication methods failed
```

**Comment by travisghansen** [comment]
OK, make sure each for parent and snapshot parent are isolated (if you didn't change the `datasetParentName` please do so and make sure the the detached snapshots are not 'beneath' it.

The `detachedSnapsots` is part of how I implemented the snapshotting feature (even if you haven't created a snapshot class, the controller broadcasts that it's capable of snapshots so k8s will invoke various csi methods associated with it regardless of your usage ATM).

What do the logs of the controller pod show? I assume you have a dataset now at least?

**Comment by travisghansen** [comment]
Also, did the share get created?

Your syntax for networks is off as well, it should be as follows:

```
[10.0.0.0/24, 10.0.1.0/24, 10.0.10.0/24, 10.42.0.0/16, 10.43.0.0/16]
```

Are your nodes on one of those networks? ^ you should only need the node network(s) added and none of the k8s internal stuff should be required.

**Comment by totallyGreg** [comment]
```  
 zfs:
      datasetParentName: zapool/NFS/test/v
      detachedSnapshotsDatasetParentName: zapool/NFS/test/s
```
Just to be clear.  zapool/NFS dataset exists, but test under it does not.  
I added the commas to the allowed networks
      ```shareAllowedNetworks: [10.0.0.0/24, 10.0.1.0/24, 10.0.10.0/24, 10.42.0.0/16, 10.43.0.0/16]```

and switched the FQDNs to an IP (10.0.0.11 is one of the freenas interfaces.) to eliminate any dns issues.  Nodes are 10.0.0.{17,18,19}

helm upgrade and then recreated the pvc.  
storageClass is still having auth errors "Error: All configured authentication methods failed"

```
❯ k describe pvc
Name:          test-pvc
Namespace:     democratic-csi
StorageClass:  test-csi
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: org.democratic-csi.nfs
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type     Reason                Age              From                                                                                                            Message
  ----     ------                ----             ----                                                                                                            -------
  Normal   ExternalProvisioning  5s               persistentvolume-controller                                                                                     waiting for a volume to be created, either by external provisioner "org.democratic-csi.nfs" or manually created by system administrator
  Normal   Provisioning          2s (x3 over 5s)  org.democratic-csi.nfs_zfs-nfs-democratic-csi-controller-7f46897d49-c8gld_bce8db3e-a634-4f88-880f-bab93d94c6c9  External provisioner is provisioning volume for claim "democratic-csi/test-pvc"
  Warning  ProvisioningFailed    2s (x3 over 5s)  org.democratic-csi.nfs_zfs-nfs-democratic-csi-controller-7f46897d49-c8gld_bce8db3e-a634-4f88-880f-bab93d94c6c9  failed to provision volume with StorageClass "test-csi": rpc error: code = Internal desc = Error: All configured authentication methods failed
```

**Comment by travisghansen** [comment]
OK cool. So you're still not getting even the dataset created at this point (this project will automatically create the parents as necessary if they don't exist).

What do you see in the controller logs?

I'm guessing at this point, the error has to do with the ssh connection for *some* reason. Maybe ssh isn't started on FreeNAS?

**Comment by totallyGreg** [comment]
You were correct, the sshd service was not allowing root to login via password.  Changed this (for now), and a dataset was created. `zapool/NFS/test/v/pvc-80c217a5-675e-4689-9730-cc6ba5ed07c5`
Now it's failing to create the NFS mount.  
```
  Warning  ProvisioningFailed    27s (x6 over 69s)  org.democratic-csi.nfs_zfs-nfs-democratic-csi-controller-7d86569cb9-vrkrb_ff471331-8152-4aeb-97de-cc95a4475066  failed to provision volume with StorageClass "test-csi": rpc error: code = Unknown desc = received error creating nfs share - code: 409 body: [object Object]
```
From controller logs. 
```
zfs-nfs-democratic-csi-controller-7d86569cb9-vrkrb csi-driver debug: zfs props data: {"mountpoint":{"value":"/mnt/zapool/NFS/test/v/pvc-80c217a5-675e-4689-9730-cc6ba5ed07c5","received":"-","source":"default"},"democratic-csi:freenas_nfs_share_id":{"value":"-","received":"-","source":"-"}}
zfs-nfs-democratic-csi-controller-7d86569cb9-vrkrb csi-driver debug: FREENAS HTTP REQUEST: {"method":"POST","url":"https://10.0.0.11/api/v1.0/sharing/nfs/","headers":{"Accept":"application/json","User-Agent":"democratic-csi-driver","Content-Type":"application/json"},"json":true,"body":{"nfs_paths":["/mnt/zapool/NFS/test/v/pvc-80c217a5-675e-4689-9730-cc6ba5ed07c5"],"nfs_comment":"democratic-csi (org.democratic-csi.nfs): zapool/NFS/test/v/pvc-80c217a5-675e-4689-9730-cc6ba5ed07c5","nfs_network":"10.0.0.0/24,10.0.1.0/24,10.0.10.0/24","nfs_hosts":"","nfs_alldirs":false,"nfs_ro":false,"nfs_quiet":false,"nfs_maproot_user":"root","nfs_maproot_group":"wheel","nfs_mapall_user":"","nfs_mapall_group":"","nfs_security":[]},"agentOptions":{"rejectUnauthorized":false}}
zfs-nfs-democratic-csi-controller-7d86569cb9-vrkrb csi-driver debug: FREENAS HTTP ERROR: null
zfs-nfs-democratic-csi-controller-7d86569cb9-vrkrb csi-driver debug: FREENAS HTTP STATUS: 409
zfs-nfs-democratic-csi-controller-7d86569cb9-vrkrb csi-driver debug: FREENAS HTTP HEADERS: {"server":"nginx","date":"Mon, 06 Jul 2020 21:13:07 GMT","content-type":"application/json","transfer-encoding":"chunked","connection":"close","vary":"Accept-Language, Cookie","content-language":"en"}
zfs-nfs-democratic-csi-controller-7d86569cb9-vrkrb csi-driver debug: FREENAS HTTP BODY: {"__all__":["'10.0.0.0/24,10.0.1.0/24,10.0.10.0/24' does not appear to be an IPv4 or IPv6 network"]}
zfs-nfs-democratic-csi-controller-7d86569cb9-vrkrb csi-driver error: handler error - driver: FreeNASDriver method: CreateVolume error: {"name":"GrpcError","code":2,"message":"received error creating nfs share - code: 409 body: [object Object]"}
zfs-nfs-democratic-csi-controller-7d86569cb9-vrkrb external-provisioner I0706 21:13:07.295829       1 connection.go:183] GRPC response: {}
```

**Comment by travisghansen** [comment]
Ah the lovely `[object Object]` error. This is just a flawless experience for you so far lol.

The is probably more crazy API stuff with FreeNAS. Even with only 2 or 3 calls they still break shit...gah.

Just for kicks can you add the following into the `httpConnection` block:

```
apiVersion: 2
```

This tells the controller to actually use the newer FreeNAS API. In actuality this project is really a bit of a matrix of support..so when I programmed everything up I actually wired in support for both version 1 and version 2 of the FreeNAS API. I'm guessing somewhere between 11.2 and 11.3 they changed how version 1 of the API works (I mean, seriously) so maybe version 2 will work better with newer builds..

**Comment by totallyGreg** [comment]
I am so hating FreeNAS these days I am contemplating setting up a ZFS SA off of Oracles demo appliance image.  

Setting `apiVersion: 2` fixed it.  

```
❯ k get pvc
NAME       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
test-pvc   Bound    pvc-774e6c5a-c603-4039-b507-969900ace4fe   1Mi        RWX            test-csi       50s
❯ k get pv pvc-774e6c5a-c603-4039-b507-969900ace4fe
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                     STORAGECLASS   REASON   AGE
pvc-774e6c5a-c603-4039-b507-969900ace4fe   1Mi        RWX            Delete           Bound    democratic-csi/test-pvc   test-csi                119s
```
Now to work on figuring out how to set a sane service account so I'm not doing everything through root... 

Thank you for your help.  I'd be interested in helping make the helm chart more robust if you like.

**Comment by travisghansen** [comment]
Yeah. Well that was fun. I like FreeNAS generally, but using the API has been abysmal. This platform also works with generic ZoL on Ubuntu if you decide to go that route...it's actually quite a nice setup to use for this purpose (others maybe not so much).

Regarding `root` I unfortunately don't have a comprehensive set of commands invoked but it's pretty limited (`zfs`, `chmod`, `chown`, etc). I never quite understood the issue though as honestly the http API can be completely destructive as well (which is the only thing IMO that **really** matters with a storage system).

I'm working on a couple code tweaks right now actually with this project, and help with the charts would be fantastic. Here are the items I have on my list regarding the charts:

- make chart work with multiple storage classes (currently wiping newline resulting in invalid yaml)
- remove need for iscsi dir on non iscsi deployments
- rework snapshot support to work with beta APIs

With all that out of the way, some other things to note:

- You must know what you're doing using nfs4, but if there's not a specific use-case I'd suggest against it (to me it makes little to no sense with containers especially)
- Since you're using rancher, make note of this if you try iscsi: https://github.com/rancher/rke/issues/1846
- Generally node prep requirements are exactly the same as you find here: https://netapp-trident.readthedocs.io/en/stable-v20.04/kubernetes/operations/tasks/worker.html

If you're interested in getting involved even more the next thing I want to put together is a `zfs-ephemeral` driver. Details here: https://kubernetes-csi.github.io/docs/ephemeral-local-volumes.html

**Comment by travisghansen** [comment]
I've cleaned up the charts substantially as well as fixed several minor issues and implemented a new `ephemeral inline` driver that uses node-local zfs pool.
